### ISSUE TITLE
copy_generated_to does not copy if the file is already there

### ISSUE THREAD

**Issue by dlehavi-resonai** [resonai/ybt#107]
Two important points:

1. What this means in practice is that if you are changing a proto, you must erase it's copy from build/gen in order for what ever is there to change. Moreover, if you are changing a proto and then reverting the change, you have to erase the copy from build/gen, and run with --no-build-cache (because otherwise it is not even generated), which is a small nightmare.
2. This problem will "magically disappear" if we use the build environment=debug environment suggestion.

**Comment by dlehavi-resonai** [comment]
The culprit here is link_func in utils.py, which fails silently if the file exists.

**Comment by itamaro** [comment]
the underlying culprit here is the fact that when a generated code file is regenerated (because of a proto edit), the original generated file is deleted and the new one is created (instead of modifying in-place), which breaks the assumption of `link_func` that an existing hard-link at the same FS location points to the same file :-(

this assumption is true only for links to files under the source tree (most of the time? always?), and is important for performance.

fix options:

1. drop the assumption - always delete the link and recreate it (safe, significant performance hit)
2. drop the assumption - always check that source and link point at the same FS node, and if not - delete & recreate (safe, also significant performance hit - need to compare hit between 1 & 2)
3. create separate link_func's for source files & generated files that do different things and call the correct one in each context (no performance hit for common case. not safe because it passes the responsibility to choose the right function to builder developer, which will cause copy-paste bugs)
4. apply heuristic - if source is under yabtwork then always delete & relink, otherwise use current logic (probably safe, no performance hit for common case)

I think option 4 is good, unless I'm missing something or someone else has magic option 5.
