### ISSUE TITLE
Check why linking order is not stable.

### ISSUE THREAD

**Issue by dana-resonai** [resonai/ybt#155]
link flags are supposed to be sorted by "stable topological sort", which means that if 2 libraries don't depend on each other their relative order should be stable (lexicographic) even when deps change (as long as dep-structure doesn't change).

But we saw cases of two different builds for the same target A that the link flags order of targets B and C was different when B and C don't depend on each other.
For example, builds of two different targets that depend (not directly) on target A. In  one build B was linked before C and in the second C was linked before B. Of course the dependency graph was not the same because we had different targets.

Check why this isn't stable. Start by adding a test to the function `stable_reverse_topological_sort` in `yabt/graph.py`.

**Comment by dlehavi-resonai** [comment]
- I don't understand why this algorithm is stable under working on sub-DAGs, which is our requirement. I do see why using Kahns algorithm would do this - seehttps://en.wikipedia.org/wiki/Topological_sorting#Kahn's_algorithm . A test *has to take the sub-DAGs problem into account)
- As far as I can tell the yield mechanism hinders the complexity (one traverses the edges from a node several times). I also don't see the point of complicating the algorithm with the yield when one has to scan the entire graph anyway.

**Comment by dlehavi-resonai** [comment]
- I don't see why this would be stable and moving to a sub-DAGs (I think it wouldn't), and for us this is a use case . I do see why [Kahn's algorithm](https://en.wikipedia.org/wiki/Topological_sorting#Kahn's_algorithm) would be, so lets change the algorithm. A test has to test for this.
- As far as I can tell, using yield in the middle of the loop here hinders the complexity, since one traverses the neighbors of each note the degree of this node twice. While doing so it also - in my opinion - hinders the complexity. There is no real benefit since we are traversing the entire list anyway,

**Comment by dlehavi-resonai** [comment]
This was resolved in PR #171
