### ISSUE TITLE
PythonApp target doesn't seem to have an extra arguments parameter

### ISSUE THREAD

**Issue by shirl-resonai** [resonai/ybt#183]
Situation: I have two targets that use the same script with slightly different dependencies. To switch between the dependencies, the script takes a boolean flag, `--use_alternate_stuff`, which defaults to False. In the PythonTest target we have the nice ability to switch between the two options by defining `test_flags=['--use_alternate_stuff']`, but for the PythonApp, no such option exists. Which means, if the user doesn't know he/she needs to _always_ pass this argument to the script, the script will fail. Can we make it nicer for him/her and pass this argument as part of the `runtime_params` or something similar?

@dana-resonai

**Comment by dana-resonai** [comment]
As I understand, `runtime_params` are params passed to the docker and not to the command we run inside it.
I couldn't find a way to pass argument to the command inside the docker. there is the `docker_cmd` prop but it needs to contain the command itself and not only its flags.
@itamaro Is there something I am missing?

**Comment by itamaro** [comment]
this is by design.

`PythonApp` produces an executable artifact, equivalent to a binary. it does not, and should not, hide inside it additional flags that are passed to the binary - the user has control over flags at invocation time. if extra flags were passed inside the call to docker run, it would result surprising and unexpected behavior when the user tries invoking it with more flags that could be conflicting with the "hidden flags".

such flags should be explicitly passed at invocation time, or the default values of the flags should be changed if appropriate.

**Comment by shirl-resonai** [comment]
I don't see a reason why an executable artifact shouldn't be defined with a hardcoded flag:
The surprising and unexpected behavior in this case would be if the user ran this executable and _did not_ pass this flag. There is an other executable running the same script without the flag and the dependencies that are germane to it. The only difference between the two flows is the instantiation and imports, so it is reasonable for them to reside in a single script. It is also reasonable to provide the user a way to run each flow (hence the PythonApp executables which bring the respective dependencies). It is also strange to make this design decision considering that the same arguments can be made of the PythonTest targets where the desired behavior is supported.

**Comment by itamaro** [comment]
consider a world with no ybt and docker - you have one Python script with main and flags - how would you achieve your desired behavior?

**Comment by shirl-resonai** [comment]
Not much differently from what I am proposing. There would be two separate Dockerfiles, each defining a particular set of dependencies. Then to run the script properly it has to be made aware of which dependencies it is running with, either by a flag or by some detection logic (this seems ugly to me). But this flag always has to be consistent with the Dockerfile where the application is running (i.e. 2 of 4 configurations are valid), else the dependency logic will be broken and the script will fail. This is why it makes sense to define the targets as such.

**Comment by itamaro** [comment]
PR #184 exposes `docker_cmd` prop on all "app" builders, which should give you the desired behavior by adding `docker_cmd=['--use_alternate_stuff']` to your target.

That said, admitting lacking context on what you're trying to do, it sounds like an anti-pattern (or at least some code smell), if a script must accept a certain flag in order to work, and I encourage you to find a "better way".

**Comment by shirl-resonai** [comment]
Thanks.
